# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fib_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibonacciresults',
            name='time_taken',
            field=models.CharField(max_length=255),
        ),
    ]
